CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

ALTER TABLE data_items
ADD COLUMN created_by INT,
ADD FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE;
